server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://mysql.qiqiang.com:3307/qim
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
naming:
  zookeeper: zookeeper.qiqiang.com:2181
im-store:
  type: redis